### PR TITLE
Added backwards compatible fixes for Blender 2.8 and up.

### PR DESCRIPTION
**Pull request by aehrath-gretel**
I went through and fixed all the spots where Blender2.8 and up failed. I added a test to see if we are version less than 2.8 and run the original code when that is the case.

### CODE REVIEW

**Comment by ConstantinosM** [comment]
Thanks a lot @aehrath-gretel  for this! I am a complete beginner in Blender and it took me few days to get to the proper modifications needed. Your changes saved my time!

Do you know why there is a difference in the rendering result? I used just a numpy array as input.
2.8:
image

2.79:
 
image

The 2.8 version seems "washed out".

Any help would be great!

**Comment by aehrath-gretel** [comment]
Oh I can take a look when I get a chance.
Looks like a lighting issue.

**Comment by ConstantinosM** [comment]
Thank you so much! I experimented a bit with the render engines and I share with you few things that maybe you find useful:
I changed the Render engine in 2.8 to Cycles and the result looked more similar to the 2.7 version. I chose also these:
image
The best image I could get was:
image
 Not that close to the one rendered with 2.79 but it's an improvement.

**Comment by codingdna2** [comment]
Hi, late to the party here... 
I've tested the modifications of this PR using Blender 2.93.4 and I've got the same "washed out" result.
I've changed the `create_lamp` as following:
```python
def create_lamp(origin, type='POINT', energy=2.5, color=(1,1,1), target=None):
    if bpy.app.version < (2, 80, 0):
        bpy.ops.object.add(type='LAMP', location=origin)
        obj = bpy.context.object
        obj.data.type = type
        obj.data.energy = energy
        obj.data.color = color
    else:
        bpy.ops.object.light_add(type=type, location=origin)
        obj = bpy.context.object
        obj.data.type = type
        obj.data.energy = energy
        obj.data.color = color

    if target: track_to_constraint(obj, target)
    return obj
```

**Comment by njanakiev** [comment]
Thanks for the fix and backward compatibility @aehrath-gretel!

**Pull request merged**
